name: SuiteRetail
favicon: null
layout_spectrum: 0.3040621
typography_spectrum: 0.6600956
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e64b27'
    - '#000000'
    - '#9f9f9f'
    - '#6f6f6f'
  brandStrength: 0.625
  lightness: 0.6539544
  saturation: 0.306722
  rhythmicContrast: 0.1132911
purpose: []
