name: SuiteRetail
favicon: null
layout_spectrum: 0.33226
typography_spectrum: 0.72858
title: SuitePOS for NetSuite and Salesforce
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#b4b4b4'
    - '#424242'
    - '#909090'
  brandStrength: 0.625
  lightness: 0.6539544
  saturation: 0.306722
  rhythmicContrast: 0.1132911
purpose: []
